import { describe, expect, it } from "vitest";

import { classifyUserText } from "../src/transcript/classify.js";

describe("classifyUserText", () => {
  it.each([
    ["continue", "continue"],
    ["  Yes.  ", "continue"],
    ["ok!", "continue"],
    ["go ahead", "continue"],
    ["keep going", "continue"],
    ["no, use the other table", "correction"],
    ["Wrong file", "correction"],
    ["that's not what I asked", "correction"],
    ["don't push yet", "correction"],
    ["actually, skip the tests", "correction"],
    ["build the scorer next", "other"],
    ["nothing to add", "other"],
  ])("the user prompt %j is %s", (text, sub) => {
    expect(classifyUserText(text)).toEqual({ kind: "user", sub });
  });

  it.each([
    "Base directory for this skill: /Users/dev/.claude/skills/x",
    "<command-name>/clear</command-name>",
    "<command-message>review</command-message>",
    "<local-command-stdout>done</local-command-stdout>",
    "<system-reminder>hi</system-reminder>",
    "<task-notification>agent done</task-notification>",
    "Caveat: The messages below were generated by the user while running local commands.",
    "This session is being continued from a previous conversation.",
    "<bash-input>ls</bash-input>",
    "<bash-stdout>x</bash-stdout>",
    "   ",
  ])("machine text %j is not the user", (text) => {
    expect(classifyUserText(text)).toEqual({ kind: "machine" });
  });

  it("detects interrupts", () => {
    expect(classifyUserText("[Request interrupted by user for tool use]")).toEqual({ kind: "interrupt" });
    expect(classifyUserText("[Request interrupted by user]")).toEqual({ kind: "interrupt" });
  });

  it("classifies a teammate idle notification", () => {
    const text = 'Another Claude session sent a message:\n<teammate-message teammate_id="fix-1" color="blue">\n{"type":"idle_notification","from":"fix-1"}\n</teammate-message>';
    expect(classifyUserText(text)).toEqual({ kind: "teammate", sub: "idle", from: "fix-1" });
  });

  it("classifies a teammate shutdown as terminate", () => {
    const text = '<teammate-message teammate_id="a">{"type":"shutdown_approved"}</teammate-message>';
    expect(classifyUserText(text)).toEqual({ kind: "teammate", sub: "terminate", from: "a" });
  });

  it("classifies teammate prose and JSON of other types as text", () => {
    expect(classifyUserText('<teammate-message teammate_id="a">PR #12 is up</teammate-message>')).toEqual({ kind: "teammate", sub: "text", from: "a" });
    expect(classifyUserText('<teammate-message teammate_id="a">{"type":"status"}</teammate-message>')).toEqual({ kind: "teammate", sub: "text", from: "a" });
  });

  it("handles a wrapper with no teammate id", () => {
    expect(classifyUserText("<teammate-message>hello</teammate-message>")).toEqual({ kind: "teammate", sub: "text", from: null });
  });

  it("classifies a cross-session message without a teammate tag as teammate text", () => {
    expect(classifyUserText("Another Claude session sent a message:\nplain")).toEqual({ kind: "teammate", sub: "text", from: null });
  });
});
