#!/usr/bin/env bash
# sync-rules.sh — link per-provider rule locations to canonical .agents/rules/.
#
# Usage: sync-rules.sh [--check] [--force] [repo-dir]
#
# Canonical source: <repo>/.agents/rules/<name>.md. One file serves every provider, so its
# frontmatter carries each provider's key (each ignores the others):
#   ---
#   description: One line describing when the rule applies   # Cursor
#   globs:                                                    # Cursor
#     - "src/**/*.ts"
#   paths:                                                    # Claude Code (same list as globs)
#     - "src/**/*.ts"
#   alwaysApply: false                                        # Cursor; true when there are no globs
#   ---
#
# Links (no copies):
#   .claude/rules              -> ../.agents/rules            Claude Code
#   .cursor/rules/<name>.mdc   -> ../../.agents/rules/<name>.md   Cursor (needs the .mdc extension)
#   CLAUDE.md                  -> AGENTS.md                   Claude Code (created if absent)
# Generates:
#   AGENTS.md rules index      Codex has no glob-scoped rules; the table is its routing layer.
#
# --check  write nothing; exit 1 if a link is missing, the index is stale, or globs != paths.
# --force  replace an existing real .claude/rules dir or hand-written .cursor/rules/<name>.mdc.

set -euo pipefail

CHECK=false
FORCE=false
REPO=""
for arg in "$@"; do
  case "$arg" in
    --check) CHECK=true ;;
    --force) FORCE=true ;;
    -h|--help) sed -n '2,25p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    -*) echo "sync-rules: unknown flag $arg" >&2; exit 2 ;;
    *) REPO="$arg" ;;
  esac
done
REPO="${REPO:-$(pwd)}"
REPO="$(cd "$REPO" && pwd)"

SRC="$REPO/.agents/rules"
AGENTS_MD="$REPO/AGENTS.md"
INDEX_START="<!-- === RULES INDEX START (generated by sync-rules.sh — edit .agents/rules/, then run scripts/sync-rules.sh) === -->"
INDEX_END="<!-- === RULES INDEX END === -->"

if [ ! -d "$SRC" ]; then
  echo "sync-rules: no canonical rules at $SRC" >&2
  exit 1
fi

TMP="$(mktemp -d "${TMPDIR:-/tmp}/sync-rules.XXXXXX")"
trap 'rm -rf "$TMP"' EXIT

CHANGED=0
FAILED=0

# report MSG — record a needed change (printed in --check mode, applied otherwise).
report() { CHANGED=1; echo "$1"; }

# link TARGET DEST — make DEST a symlink to TARGET (relative), respecting --check/--force.
link() {
  local target="$1" dest="$2" rel="${2#"$REPO"/}"
  if [ -L "$dest" ] && [ "$(readlink "$dest")" = "$target" ]; then
    return 0
  fi
  if [ -e "$dest" ] && [ ! -L "$dest" ] && [ "$FORCE" != true ]; then
    echo "sync-rules: WARN $rel exists and is not a link — skipped (use --force to replace)" >&2
    FAILED=1
    return 0
  fi
  if [ "$CHECK" = true ]; then
    report "not linked: $rel -> $target"
    return 0
  fi
  mkdir -p "$(dirname "$dest")"
  rm -rf "$dest"
  ln -s "$target" "$dest"
  report "linked: $rel -> $target"
}

# list_key FILE KEY — print KEY's list entries (block `- x`, inline `[a, b]`, or `a, b`), one per line.
list_key() {
  awk -v key="$2" '
    function unq(s) {
      sub(/^[ \t]+/, "", s); sub(/[ \t]+$/, "", s)
      if (s ~ /^".*"$/ || s ~ /^\x27.*\x27$/) s = substr(s, 2, length(s) - 2)
      return s
    }
    NR == 1 { if ($0 != "---") exit; infm = 1; next }
    infm && $0 == "---" { exit }
    infm {
      line = $0
      if (line ~ /^[ \t]*#/ || line ~ /^[ \t]*$/) next
      if (index(line, key ":") == 1) {
        sub("^" key ":[ \t]*", "", line); sub(/[ \t]+#.*$/, "", line)
        inlist = 1
        if (line != "") {
          sub(/^\[/, "", line); sub(/\][ \t]*$/, "", line)
          n = split(line, parts, ",")
          for (i = 1; i <= n; i++) { g = unq(parts[i]); if (g != "") print g }
          inlist = 0
        }
        next
      }
      if (inlist && line ~ /^[ \t]*-[ \t]*/) { sub(/^[ \t]*-[ \t]*/, "", line); g = unq(line); if (g != "") print g; next }
      inlist = 0
    }
  ' "$1"
}

# scalar_key FILE KEY — print KEY's scalar value from the frontmatter.
scalar_key() {
  awk -v key="$2" '
    NR == 1 { if ($0 != "---") exit; next }
    $0 == "---" { exit }
    index($0, key ":") == 1 {
      v = substr($0, length(key) + 2); sub(/^[ \t]+/, "", v); sub(/[ \t]+$/, "", v)
      if (v ~ /^".*"$/ || v ~ /^\x27.*\x27$/) v = substr(v, 2, length(v) - 2)
      print v; exit
    }
  ' "$1"
}

# --- Claude Code: the whole rules dir is one link.
link "../.agents/rules" "$REPO/.claude/rules"

# --- Cursor: one .mdc link per rule; drop our links whose source is gone.
INDEX_ROWS="$TMP/index-rows"
: > "$INDEX_ROWS"
for src in "$SRC"/*.md; do
  [ -e "$src" ] || continue
  name="$(basename "$src" .md)"
  link "../../.agents/rules/$name.md" "$REPO/.cursor/rules/$name.mdc"

  list_key "$src" globs > "$TMP/$name.globs"
  list_key "$src" paths > "$TMP/$name.paths"
  if ! cmp -s "$TMP/$name.globs" "$TMP/$name.paths"; then
    echo "sync-rules: ERROR .agents/rules/$name.md — 'globs' (Cursor) and 'paths' (Claude Code) must list the same patterns" >&2
    FAILED=1
  fi

  desc="$(scalar_key "$src" description)"
  if [ -s "$TMP/$name.globs" ]; then
    applies="$(sed 's/|/\\|/g; s/^/`/; s/$/`/' "$TMP/$name.globs" | paste -sd ',' - | sed 's/,/, /g')"
  else
    applies="always"
  fi
  printf '| `%s` | %s | %s | `.agents/rules/%s.md` |\n' "$name" "$(printf '%s' "$desc" | sed 's/|/\\|/g')" "$applies" "$name" >> "$INDEX_ROWS"
done
for dest in "$REPO"/.cursor/rules/*.mdc; do
  [ -L "$dest" ] || continue
  case "$(readlink "$dest")" in ../../.agents/rules/*) ;; *) continue ;; esac
  [ -e "$dest" ] && continue
  if [ "$CHECK" = true ]; then report "stale: ${dest#"$REPO"/}"; else rm -f "$dest"; report "removed: ${dest#"$REPO"/}"; fi
done

# --- AGENTS.md rules index (Codex).
if [ -f "$AGENTS_MD" ]; then
  block="$TMP/index-block"
  {
    echo "$INDEX_START"
    echo "## Rules Index"
    echo
    echo "Domain rules live in \`.agents/rules/\`. Before editing a file, read every rule below whose globs match it (\"always\" rules apply to every task). Claude Code and Cursor load them automatically through \`.claude/rules\` and \`.cursor/rules/\` links; Codex does not — read them yourself."
    echo
    echo "| Rule | Description | Applies to | Path |"
    echo "|------|-------------|------------|------|"
    cat "$INDEX_ROWS"
    echo "$INDEX_END"
  } > "$block"
  new="$TMP/AGENTS.md"
  if grep -qF "RULES INDEX START" "$AGENTS_MD"; then
    awk -v blockfile="$block" '
      /RULES INDEX START/ { while ((getline l < blockfile) > 0) print l; skip = 1; next }
      skip && /RULES INDEX END/ { skip = 0; next }
      !skip { print }
    ' "$AGENTS_MD" > "$new"
  else
    { cat "$AGENTS_MD"; echo; cat "$block"; } > "$new"
  fi
  if ! cmp -s "$new" "$AGENTS_MD"; then
    if [ "$CHECK" = true ]; then report "out of date: AGENTS.md rules index"; else cp "$new" "$AGENTS_MD"; report "wrote: AGENTS.md rules index"; fi
  fi
  # CLAUDE.md: Claude Code reads CLAUDE.md, not AGENTS.md, so link it.
  link "AGENTS.md" "$REPO/CLAUDE.md"
else
  echo "sync-rules: WARN no AGENTS.md at repo root — rules index and CLAUDE.md link not written" >&2
  FAILED=1
fi

if [ "$CHECK" = true ] && { [ "$CHANGED" = 1 ] || [ "$FAILED" = 1 ]; }; then
  echo "sync-rules: out of date — run scripts/sync-rules.sh" >&2
  exit 1
fi
[ "$CHANGED" = 0 ] && [ "$FAILED" = 0 ] && echo "sync-rules: up to date"
exit "$FAILED"
